#application: comic-lib1
#version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /styles
  static_dir: styles

- url: .*
  script: handlers.index.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: PIL
  version: latest
- name: pycrypto
  version: latest